import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;

public class CustomCustomsTobias {
    public static void main(String[] args) {
        answerOne();
        answerTwo();
    }

    private static void answerOne() {
        List<Integer> sumList = Arrays.stream(getInput().split("\n\n")).map(s -> s.replaceAll("\n", "")).map(s -> {
            Stream<Character> cStream = IntStream.range(0, s.toCharArray().length).mapToObj(i -> s.toCharArray()[i]);
            return cStream.distinct().toArray(Character[]::new).length;
        }).collect(Collectors.toList());
        Integer sum = sumList.stream().reduce(0, (a, b) -> a + b);
        System.out.println("Sum: " + sum);
    }

    private static void answerTwo() {
        List<Integer> sumList2 = Arrays.stream(getInput().split("\n\n")).map(s -> {
            Integer numberOfPerson = s.split("\n").length;
            String finalString = s.replaceAll("\n", "");
            char[] finalCharArray = finalString.toCharArray();
            Stream<Character> cStream = IntStream.range(0, finalCharArray.length).mapToObj(i -> finalCharArray[i]);
            Character[] distinctCharacter = cStream.distinct().toArray(Character[]::new);
            Integer sumPerson = Arrays.stream(distinctCharacter).map(z -> (int) IntStream.range(0, finalCharArray.length).mapToObj(i -> finalCharArray[i]).filter(c -> c == z).count() / numberOfPerson).reduce(0, (a, b) -> a + b);
            return sumPerson;
        }).collect(Collectors.toList());
        Integer sumTwo = sumList2.stream().reduce(0, (a, b) -> a + b);
        System.out.println("Sum2: " + sumTwo);
    }

    public static String getSample() {
        return "abc\n" +
                "\n" +
                "a\n" +
                "b\n" +
                "c\n" +
                "\n" +
                "ab\n" +
                "ac\n" +
                "\n" +
                "a\n" +
                "a\n" +
                "a\n" +
                "a\n" +
                "\n" +
                "b";
    }

    public static String getInput() {
        return "qzbw\n" +
                "qez\n" +
                "\n" +
                "xgedfibnyuhqsrazlwtpocj\n" +
                "fxgpoqijdzybletckwaunsr\n" +
                "pwnqsizrfcbyljexgouatd\n" +
                "ljtperqsodghnufiycxwabz\n" +
                "\n" +
                "uk\n" +
                "kupacjlriv\n" +
                "dku\n" +
                "qunk\n" +
                "\n" +
                "yjnprofmcuhdlawt\n" +
                "frmhulyncvweatodzjp\n" +
                "fhadtrcyjzwlnpumo\n" +
                "hrcutablndyjpfmwo\n" +
                "\n" +
                "rdclv\n" +
                "lrvdc\n" +
                "crldv\n" +
                "dvrcl\n" +
                "vrlcd\n" +
                "\n" +
                "dqrwajpb\n" +
                "asrfpdjwbq\n" +
                "wjdtarq\n" +
                "\n" +
                "nalkhgoi\n" +
                "bmiad\n" +
                "sdvpiyerma\n" +
                "ami\n" +
                "\n" +
                "smg\n" +
                "wlmdftcr\n" +
                "mk\n" +
                "my\n" +
                "\n" +
                "ebaxsun\n" +
                "uaxnebs\n" +
                "suxnbea\n" +
                "eanxusb\n" +
                "aexusnb\n" +
                "\n" +
                "zoxegrfd\n" +
                "qorjv\n" +
                "oqr\n" +
                "vor\n" +
                "roq\n" +
                "\n" +
                "jpasdnrcvhglft\n" +
                "dgkstavnhjrclfx\n" +
                "crtndjglfvwahq\n" +
                "hjclinvdtagrkf\n" +
                "gjfcdtuhlanvr\n" +
                "\n" +
                "exiopqbgrj\n" +
                "undhwyfkvltis\n" +
                "\n" +
                "npsxwlyog\n" +
                "udylki\n" +
                "\n" +
                "bnuwck\n" +
                "nuack\n" +
                "\n" +
                "cahpwtlozkm\n" +
                "ghnpzfqmoxabi\n" +
                "\n" +
                "hvwgxesraocbpnf\n" +
                "ewvranqcpbghoxf\n" +
                "paxfnwoegrhcvub\n" +
                "qbrawpfscexngvho\n" +
                "ahpxognlrvebwfc\n" +
                "\n" +
                "agqmwpvlb\n" +
                "waklrnbqyp\n" +
                "blquawtp\n" +
                "qltabwp\n" +
                "\n" +
                "rymhgolkustipjxbzqnafe\n" +
                "frzqjiuktbsxmahdepylg\n" +
                "\n" +
                "zricqdofygvtbsjmeu\n" +
                "vudjctzynegboiafqmrsx\n" +
                "rsbefoytcqgiuvzdjm\n" +
                "zucobitsgyjrfqemvd\n" +
                "\n" +
                "y\n" +
                "yc\n" +
                "tg\n" +
                "lavoqef\n" +
                "by\n" +
                "\n" +
                "fevykin\n" +
                "wxytrhqk\n" +
                "\n" +
                "pxbclzknowyq\n" +
                "lybwkpcoqxn\n" +
                "oknlpbxcyqw\n" +
                "\n" +
                "l\n" +
                "f\n" +
                "gixvd\n" +
                "\n" +
                "unogwsfavzkhi\n" +
                "siohufnkzgavw\n" +
                "ahitunswfvkzog\n" +
                "gvhknzuaisfow\n" +
                "ukasozfihnwgv\n" +
                "\n" +
                "ulhgwo\n" +
                "ghluo\n" +
                "ogulh\n" +
                "oughl\n" +
                "lphuog\n" +
                "\n" +
                "nike\n" +
                "bkn\n" +
                "\n" +
                "gefzwrdjsqx\n" +
                "fegzsjwxrpqh\n" +
                "\n" +
                "lfknweboxyrpajmig\n" +
                "gkpafnieojybrwl\n" +
                "iafesdyulrkpgnwbjo\n" +
                "\n" +
                "zjoiqtgpwxdach\n" +
                "iajdhqucpxtzgl\n" +
                "\n" +
                "yhav\n" +
                "vnshac\n" +
                "hcav\n" +
                "hvw\n" +
                "cyvh\n" +
                "\n" +
                "hwz\n" +
                "whz\n" +
                "\n" +
                "dhunracmzksvxopjgtbqi\n" +
                "vqhpowubyzirdksmgca\n" +
                "\n" +
                "ckrhefz\n" +
                "rkvexdfzcbh\n" +
                "heczkrf\n" +
                "\n" +
                "rbsldt\n" +
                "qgr\n" +
                "\n" +
                "a\n" +
                "ea\n" +
                "a\n" +
                "\n" +
                "wnadxkgehtpsv\n" +
                "gwnexkavshpd\n" +
                "bfkdpansvhewxg\n" +
                "kvtwdnsahpxge\n" +
                "xnhdpvekwgsa\n" +
                "\n" +
                "ydajvctr\n" +
                "drcejtgin\n" +
                "\n" +
                "kw\n" +
                "cbmj\n" +
                "l\n" +
                "t\n" +
                "n\n" +
                "\n" +
                "gyzlnp\n" +
                "zahsyu\n" +
                "rek\n" +
                "\n" +
                "vjdmhsorqw\n" +
                "whdjoqvrms\n" +
                "rhsjqdmov\n" +
                "omdsqjrzhv\n" +
                "\n" +
                "rcxsgnluhtqey\n" +
                "ldejuqpykrtc\n" +
                "\n" +
                "rylcqxt\n" +
                "wlgtzyrcf\n" +
                "yrltc\n" +
                "rclpyt\n" +
                "\n" +
                "frke\n" +
                "kfe\n" +
                "\n" +
                "nchvxtqarsejld\n" +
                "rkhntaexcbqljod\n" +
                "qhdepzrxljtifcan\n" +
                "\n" +
                "uyfshgxzbqvrdwintjlmec\n" +
                "oyrvdwtgeczsfbmluqih\n" +
                "kabdlqytwgfrhmuevczpsi\n" +
                "\n" +
                "guwmkrfyex\n" +
                "fxekmrygwu\n" +
                "wfgremukiyx\n" +
                "aywegkrmxufl\n" +
                "wukygimrxfe\n" +
                "\n" +
                "m\n" +
                "m\n" +
                "m\n" +
                "m\n" +
                "m\n" +
                "\n" +
                "hbgnkqe\n" +
                "khgn\n" +
                "\n" +
                "hngypzmd\n" +
                "oixyanpdg\n" +
                "\n" +
                "qbdklpvhjaeif\n" +
                "kzaiglyjfpmeurn\n" +
                "\n" +
                "ynsm\n" +
                "smjn\n" +
                "nsyum\n" +
                "\n" +
                "mpcztqkydxifv\n" +
                "zdqfvxtmpcyk\n" +
                "zkcmxfpqvydt\n" +
                "yopktfnqrmvxdczw\n" +
                "mdckxypvztqf\n" +
                "\n" +
                "va\n" +
                "bvhg\n" +
                "\n" +
                "fe\n" +
                "ef\n" +
                "\n" +
                "n\n" +
                "hpmqn\n" +
                "n\n" +
                "dn\n" +
                "\n" +
                "njxazhtevsmlir\n" +
                "txmsijvaezwn\n" +
                "tezacmwsvinxj\n" +
                "\n" +
                "gvzpbmeijyhaukflcrdqw\n" +
                "sivlhgumyzkdrjfeoxqtc\n" +
                "\n" +
                "ouq\n" +
                "h\n" +
                "\n" +
                "csxewy\n" +
                "kxoscmw\n" +
                "ucnvwsxg\n" +
                "hfocysxmiwe\n" +
                "wcsmx\n" +
                "\n" +
                "retcxugsdwjnykm\n" +
                "sfhudnxoqwjktyzarc\n" +
                "rklvinxudpsbywtjc\n" +
                "\n" +
                "cwfizpyguatbodsqemxrjknlv\n" +
                "ujikxwsmntcloyqgaebrzfdvp\n" +
                "jreyubofkpdnzsimxwvgaqtlc\n" +
                "nuewfvmlidsatzqbkcjgorpyx\n" +
                "\n" +
                "ycqolubpktxwshegafvm\n" +
                "djnlhafsreuzgxkb\n" +
                "\n" +
                "odasxjtqcepgrzl\n" +
                "jsoelxpqgtczam\n" +
                "qiajrhesdzoxfplcgt\n" +
                "\n" +
                "vnthkurzf\n" +
                "bnfpqutvekra\n" +
                "\n" +
                "gujxqsnitohp\n" +
                "tchxqjgoiu\n" +
                "\n" +
                "hgparlm\n" +
                "mjxghlqzp\n" +
                "fmlpahcg\n" +
                "\n" +
                "deptkcyasiwgfonv\n" +
                "ptqufxjhcyglrzdov\n" +
                "\n" +
                "awnxeshvrbcjm\n" +
                "xreswnhbcmvja\n" +
                "axvwnsejrmbhc\n" +
                "xajcmrnevhwbs\n" +
                "sjxhcbearmwnv\n" +
                "\n" +
                "woystmzcbgrljqhxdiukn\n" +
                "mzhlbgcwjusnortdqky\n" +
                "tunrjlzmqosygbwhkcd\n" +
                "\n" +
                "agh\n" +
                "ahg\n" +
                "agh\n" +
                "hga\n" +
                "hag\n" +
                "\n" +
                "cmzkthbquilgwypreno\n" +
                "tsmezpqlwkhrcginuo\n" +
                "gmniotwlpzyqceukrh\n" +
                "wztuikrglhqocnpme\n" +
                "ekqchwogpliumrtzn\n" +
                "\n" +
                "jqadntioypevlwcksmb\n" +
                "hymnfzcvtdaxsekrqijo\n" +
                "dvqmgiacknyoesjt\n" +
                "\n" +
                "cdnbkfzev\n" +
                "bfvdwcezk\n" +
                "kzeblcdvf\n" +
                "vfdkneczb\n" +
                "fdeovjczystkib\n" +
                "\n" +
                "rzc\n" +
                "pma\n" +
                "zwvx\n" +
                "zyrlt\n" +
                "\n" +
                "lmwvudafhnczxibsgpjkreoq\n" +
                "durlgqhmvpxofsiejwcbkzan\n" +
                "mieraklxftswzjbuocndvpqghy\n" +
                "\n" +
                "qlaxkbf\n" +
                "rfhyxtbkseaq\n" +
                "bxkqaf\n" +
                "fkxbaqn\n" +
                "\n" +
                "lpntzrufvskoqciaxhedw\n" +
                "arsztnpofkxcqudilhewv\n" +
                "srvlzcujywkenimafhtoqxp\n" +
                "\n" +
                "snxwjqapfo\n" +
                "nwsfqxpajo\n" +
                "npfqjowaxs\n" +
                "opjfxanwqs\n" +
                "sjaonwxqpf\n" +
                "\n" +
                "cswjquxv\n" +
                "uyecrkg\n" +
                "ufjcl\n" +
                "\n" +
                "qjvzl\n" +
                "jvqzl\n" +
                "lzjqv\n" +
                "qlvjz\n" +
                "\n" +
                "h\n" +
                "h\n" +
                "\n" +
                "mprvotcsgadybjfkqehz\n" +
                "bjsordtucqlgkhfzvepy\n" +
                "fsoqijpvhgkczybrted\n" +
                "yzsgkfhvcbjpeqtrdo\n" +
                "cjzdvkprbheysmofgqt\n" +
                "\n" +
                "jzontimefb\n" +
                "ldorvefxuatpj\n" +
                "\n" +
                "i\n" +
                "xi\n" +
                "\n" +
                "zhtkdvl\n" +
                "pchznv\n" +
                "jmryxuwgazvfh\n" +
                "lkdevczh\n" +
                "\n" +
                "subt\n" +
                "utsb\n" +
                "fsuobt\n" +
                "jutsb\n" +
                "utbjs\n" +
                "\n" +
                "n\n" +
                "n\n" +
                "n\n" +
                "dnk\n" +
                "\n" +
                "qkrfv\n" +
                "fqgvkseut\n" +
                "qvrfk\n" +
                "\n" +
                "w\n" +
                "x\n" +
                "n\n" +
                "n\n" +
                "\n" +
                "mkpoyfrngtwdcjlv\n" +
                "yprcuimjsz\n" +
                "rcyjzxphm\n" +
                "pjecrmyx\n" +
                "ipyramcqj\n" +
                "\n" +
                "puwnzsohkv\n" +
                "nsohwkuzvp\n" +
                "upnhokswvzx\n" +
                "\n" +
                "rmvjwzhx\n" +
                "kpxhqevglom\n" +
                "mzxfhbv\n" +
                "mhwjitfrvnx\n" +
                "mcusxhvwj\n" +
                "\n" +
                "vipkgth\n" +
                "oskhetgp\n" +
                "zlqhnbdjwgurxapc\n" +
                "\n" +
                "vn\n" +
                "vna\n" +
                "gwvdn\n" +
                "\n" +
                "rugcbipvzow\n" +
                "uogrzcvpbwi\n" +
                "\n" +
                "jwxuc\n" +
                "krngvmypl\n" +
                "jwxzi\n" +
                "qashtbedfco\n" +
                "\n" +
                "bzfyl\n" +
                "yzflb\n" +
                "fylbz\n" +
                "lyfzb\n" +
                "ylfbz\n" +
                "\n" +
                "uhkvb\n" +
                "kjhulb\n" +
                "vbkhu\n" +
                "\n" +
                "andlzobvguqsk\n" +
                "nkgvqlzbu\n" +
                "klbiezughvmxnrt\n" +
                "bunkzgljvf\n" +
                "yvkgjpwzubln\n" +
                "\n" +
                "t\n" +
                "t\n" +
                "\n" +
                "bdrjpavtiqlhxuw\n" +
                "pjmzbxidrtulcfw\n" +
                "\n" +
                "wqylp\n" +
                "mrhgfxsjcaltonedv\n" +
                "ywbkul\n" +
                "ikl\n" +
                "\n" +
                "hxpivszmbaodecnlurq\n" +
                "cedlpnibqmwxaghrszou\n" +
                "hunbrdzpsxleaitmqyco\n" +
                "\n" +
                "pymewobv\n" +
                "veazgoy\n" +
                "yvoxle\n" +
                "youfveix\n" +
                "syegdvo\n" +
                "\n" +
                "ogceirlsaqjtmvzdx\n" +
                "rtsaijxocelmzgdvq\n" +
                "dvrqjxizmgscteoal\n" +
                "\n" +
                "jeupkmhcydwaz\n" +
                "daykzechjpwmu\n" +
                "umkaejhwydpzc\n" +
                "aywkjphdzeucm\n" +
                "ypdchmujekazw\n" +
                "\n" +
                "suzacvgjnoi\n" +
                "evgsufjaitn\n" +
                "rqeanjskxbvfgiwu\n" +
                "dknubsaxgvji\n" +
                "\n" +
                "ojxfyetcpdbglmwqunrsi\n" +
                "fjletcbrdsnviogpxwuq\n" +
                "jcgprswxiaefdqnotlub\n" +
                "zfgjewrpldsioxcqntub\n" +
                "nxcgewpqolibrktujsfd\n" +
                "\n" +
                "vwh\n" +
                "hjvw\n" +
                "hvjw\n" +
                "hvwr\n" +
                "vhw\n" +
                "\n" +
                "md\n" +
                "m\n" +
                "m\n" +
                "m\n" +
                "\n" +
                "xkpu\n" +
                "izfmrosjbd\n" +
                "eywqt\n" +
                "xgak\n" +
                "hgn\n" +
                "\n" +
                "layhskgxrpfnwqmdj\n" +
                "mlsxywoakrectnzgqdjf\n" +
                "fbsxnmuikqwrljgv\n" +
                "\n" +
                "rhcn\n" +
                "lon\n" +
                "dln\n" +
                "pban\n" +
                "nhd\n" +
                "\n" +
                "uxwhl\n" +
                "hx\n" +
                "\n" +
                "aesduycrgfmhjblnkzt\n" +
                "jktlhwqioepzgcbnmda\n" +
                "\n" +
                "tbhfongxiudcrv\n" +
                "rqoyfnuxabjekl\n" +
                "\n" +
                "ajd\n" +
                "wjdmak\n" +
                "jda\n" +
                "jad\n" +
                "\n" +
                "ghimtjly\n" +
                "hjtgilm\n" +
                "ghixmjtpal\n" +
                "jtmhilg\n" +
                "imhgtjluo\n" +
                "\n" +
                "ewpfam\n" +
                "epmwa\n" +
                "epwma\n" +
                "ewamp\n" +
                "\n" +
                "cslywuzkdg\n" +
                "jfluyxgbsma\n" +
                "ugysbl\n" +
                "ytlqgaus\n" +
                "hsufgloxyr\n" +
                "\n" +
                "eigjpobrlxnasvhquwy\n" +
                "nirbjslgwyxuoaqevhp\n" +
                "fpnsuxbleoajwyhgirvq\n" +
                "ayinxhubgvweprqljso\n" +
                "\n" +
                "andu\n" +
                "sguand\n" +
                "\n" +
                "embqxktgpduyjia\n" +
                "qtjagiydempukxb\n" +
                "axswpjdgqbumyteik\n" +
                "kgaexydbupqtjmi\n" +
                "uqjbixkdptgmeya\n" +
                "\n" +
                "uxzwnlgyareost\n" +
                "nesygtowzuralx\n" +
                "lnguxsaoyzwtre\n" +
                "\n" +
                "thfobmluspeiwxygv\n" +
                "ibtfgsyouvxdpelh\n" +
                "txqerhuolbpsgfyvi\n" +
                "oehxfsmbiuvpyltg\n" +
                "pfoiuhlebvyxwdgst\n" +
                "\n" +
                "e\n" +
                "ke\n" +
                "e\n" +
                "e\n" +
                "\n" +
                "zhxyc\n" +
                "hczxy\n" +
                "ohzycx\n" +
                "\n" +
                "sylzvbx\n" +
                "sxzvlyb\n" +
                "vltysxbz\n" +
                "ylbxzsvf\n" +
                "\n" +
                "zxkt\n" +
                "xztk\n" +
                "\n" +
                "mnctogxvwkseh\n" +
                "owrsadeqmhtykcg\n" +
                "matkscwo\n" +
                "mcwpzbofs\n" +
                "\n" +
                "wvpybgulfrhnixjka\n" +
                "rgawyujfcsveki\n" +
                "\n" +
                "hbmljqxrtza\n" +
                "xmutqzahl\n" +
                "zaqlmhxtu\n" +
                "hziqlatxumc\n" +
                "\n" +
                "sjwq\n" +
                "qjws\n" +
                "wqjs\n" +
                "jqsw\n" +
                "\n" +
                "ithgcoaed\n" +
                "qtgsdohec\n" +
                "\n" +
                "puidogmhysnk\n" +
                "pgszdunhyiomk\n" +
                "gmyivhnksqodpt\n" +
                "\n" +
                "ionrt\n" +
                "yhvsiud\n" +
                "\n" +
                "xtzrljypsknh\n" +
                "jkhztpylxnrs\n" +
                "yxlkrshtpnjz\n" +
                "\n" +
                "veyflgkws\n" +
                "jwukvfeshmr\n" +
                "evfwksdz\n" +
                "fekvsw\n" +
                "vkfsew\n" +
                "\n" +
                "qbercltdyiwzpfghujxa\n" +
                "bvzlratfchxyijqewpdgu\n" +
                "hfrtqbiayzdxpwujlcge\n" +
                "ejhbpuwytgixrdzaflqc\n" +
                "phrjagczeiyxwdufltbq\n" +
                "\n" +
                "chxzbkemyjgqvltsardoi\n" +
                "osykewcidjtuvzpbqhg\n" +
                "ibqozcsvygmkedfjhtn\n" +
                "\n" +
                "czgih\n" +
                "zcg\n" +
                "\n" +
                "dpulzxtweoafsvnrykqg\n" +
                "zoasklutxwnqevyfgrd\n" +
                "vnrequfolxgtzsdawyk\n" +
                "ynurtkjfogvdqzlewsax\n" +
                "kuydfznpatgvrelxoqws\n" +
                "\n" +
                "fmpeunzs\n" +
                "sumpfzn\n" +
                "fzpmnus\n" +
                "\n" +
                "sadewmz\n" +
                "sldnwe\n" +
                "wjduetyxsh\n" +
                "\n" +
                "no\n" +
                "ou\n" +
                "oua\n" +
                "ybwdoe\n" +
                "\n" +
                "etjdmfhkvupsgob\n" +
                "zjvatuxrhomingds\n" +
                "\n" +
                "wcrpzale\n" +
                "ctyzwdsulbvmexo\n" +
                "ikecwnzlg\n" +
                "ngjwczlae\n" +
                "zlqhwgecj\n" +
                "\n" +
                "p\n" +
                "p\n" +
                "p\n" +
                "v\n" +
                "\n" +
                "x\n" +
                "i\n" +
                "p\n" +
                "x\n" +
                "bgckq\n" +
                "\n" +
                "huty\n" +
                "yatu\n" +
                "cytrqju\n" +
                "wtyu\n" +
                "\n" +
                "k\n" +
                "k\n" +
                "s\n" +
                "\n" +
                "ti\n" +
                "ut\n" +
                "ut\n" +
                "\n" +
                "ltyxj\n" +
                "vaicrwnzb\n" +
                "yegjqp\n" +
                "mjogk\n" +
                "\n" +
                "ifyupadt\n" +
                "idutaypf\n" +
                "\n" +
                "civyufabow\n" +
                "oafw\n" +
                "eawtof\n" +
                "\n" +
                "tdxrcuvqmaoblhsjfynpwigkze\n" +
                "hqfymskzljrtexwugbnacpiov\n" +
                "nymlpweztcgrhjqfuiasbkxvo\n" +
                "qxcponmlbwtvazuykfsegjrih\n" +
                "vuaoelhfcyztjpxingmbkqsrw\n" +
                "\n" +
                "zqtkcomfdyrs\n" +
                "qokdtmzyawfrlc\n" +
                "qdmzejfctykor\n" +
                "\n" +
                "qgkmhvx\n" +
                "vnqmkxlh\n" +
                "kqvhxmre\n" +
                "\n" +
                "aklnbydq\n" +
                "dqynjokaebzlu\n" +
                "kblqrdany\n" +
                "\n" +
                "znaepc\n" +
                "uthvilcm\n" +
                "cpbda\n" +
                "\n" +
                "cep\n" +
                "wgecdbpz\n" +
                "pce\n" +
                "pce\n" +
                "\n" +
                "qgtaelxzvnfr\n" +
                "vwlquxfbmhgdjzir\n" +
                "fqvryplogztx\n" +
                "krfvglqszx\n" +
                "\n" +
                "xebsp\n" +
                "vohgfurnmsa\n" +
                "dqws\n" +
                "ysl\n" +
                "eqyps\n" +
                "\n" +
                "fxnlgkjizbsupyt\n" +
                "aixlkfuwezbgcpsnh\n" +
                "\n" +
                "fliogmexzuqc\n" +
                "ygxqvoeklitmfu\n" +
                "iofxzueqmgl\n" +
                "qouifehxalmg\n" +
                "oefiuqjgdmplx\n" +
                "\n" +
                "cjqnrvu\n" +
                "cquvrn\n" +
                "vqnur\n" +
                "qvrnu\n" +
                "qwsvruxnmf\n" +
                "\n" +
                "esxbjiwnya\n" +
                "ibwnjsxyae\n" +
                "abienjwys\n" +
                "ijwaybnsep\n" +
                "ybeiasjnw\n" +
                "\n" +
                "f\n" +
                "f\n" +
                "f\n" +
                "f\n" +
                "j\n" +
                "\n" +
                "dwfgkqohamebnzly\n" +
                "vhyokaeqpufjdlb\n" +
                "ayhlqfbnoedkg\n" +
                "\n" +
                "g\n" +
                "ijur\n" +
                "ad\n" +
                "\n" +
                "oxpwmzunkjved\n" +
                "dgwxejtpzn\n" +
                "exnrwizdpljhfy\n" +
                "ekzxwdjnpt\n" +
                "\n" +
                "jghbztdkypsovc\n" +
                "arefyzdnlhwpoivbsqj\n" +
                "\n" +
                "cwvpyqnhjmsblikorx\n" +
                "ywjmvfxnbqoitdls\n" +
                "gyuloqbznavmijsxw\n" +
                "\n" +
                "tv\n" +
                "vt\n" +
                "vt\n" +
                "\n" +
                "cxvwzdbpsqnhoa\n" +
                "thoqpsvmaxcbkzlin\n" +
                "anecpvqohsxzb\n" +
                "xscpvobnaqhz\n" +
                "\n" +
                "axnrzgyvepoif\n" +
                "zovgfipynhr\n" +
                "grodvzhinfpy\n" +
                "rnipgfojyhvz\n" +
                "\n" +
                "pbmhlxwqfezrscdtykn\n" +
                "cfmbkwtnlryzqehxpsd\n" +
                "qrbylwtdnsckzefxhmp\n" +
                "\n" +
                "zkqw\n" +
                "wzkq\n" +
                "jqwxzk\n" +
                "\n" +
                "vrdnmyfspbzlxw\n" +
                "izepalkytdnfcxjwhg\n" +
                "nxuwdfqzlyp\n" +
                "\n" +
                "bc\n" +
                "cb\n" +
                "\n" +
                "bf\n" +
                "fb\n" +
                "bfh\n" +
                "efbq\n" +
                "\n" +
                "amw\n" +
                "mpa\n" +
                "maw\n" +
                "\n" +
                "bqwtvl\n" +
                "vlzwtq\n" +
                "ytlqv\n" +
                "zvlqtb\n" +
                "tlqxvc\n" +
                "\n" +
                "lbhxpnkiurmwates\n" +
                "fuwrqbeztjmlpsnxaik\n" +
                "\n" +
                "jpwm\n" +
                "zwljp\n" +
                "jwmp\n" +
                "\n" +
                "zep\n" +
                "cep\n" +
                "pe\n" +
                "\n" +
                "mzx\n" +
                "zmx\n" +
                "xzbck\n" +
                "\n" +
                "dlmvbnupathgjsf\n" +
                "blknfsvtjpgmhdu\n" +
                "pnufdgmhsqtbljv\n" +
                "ijeoufmnchvysrlwzpgtdb\n" +
                "xvpudhgsjmlnbtkf\n" +
                "\n" +
                "cnyuhkmbswzilxovjp\n" +
                "ybjtdewvsrfcznalqhgiku\n" +
                "\n" +
                "bi\n" +
                "rzla\n" +
                "j\n" +
                "\n" +
                "graezckvnqx\n" +
                "agwzkcqnxre\n" +
                "grzxeckaqn\n" +
                "ghercxazknq\n" +
                "rzqakdgexcns\n" +
                "\n" +
                "sfe\n" +
                "b\n" +
                "f\n" +
                "xpjtuand\n" +
                "boies\n" +
                "\n" +
                "kgjfzqlwic\n" +
                "rkcdstgp\n" +
                "\n" +
                "fgsndtox\n" +
                "zodnyxlgts\n" +
                "otxdsgn\n" +
                "nxtfgodis\n" +
                "\n" +
                "zwrtohqdey\n" +
                "teqwry\n" +
                "pvytwegf\n" +
                "ltioweyrc\n" +
                "myeaxntuw\n" +
                "\n" +
                "bw\n" +
                "bw\n" +
                "bw\n" +
                "bw\n" +
                "fbw\n" +
                "\n" +
                "o\n" +
                "gh\n" +
                "\n" +
                "owadmhy\n" +
                "admhoyw\n" +
                "wmohyda\n" +
                "\n" +
                "nywib\n" +
                "ceulqpzh\n" +
                "\n" +
                "zs\n" +
                "sz\n" +
                "zs\n" +
                "zsko\n" +
                "szr\n" +
                "\n" +
                "izaqf\n" +
                "uijrf\n" +
                "infgq\n" +
                "\n" +
                "w\n" +
                "qw\n" +
                "m\n" +
                "bzr\n" +
                "o\n" +
                "\n" +
                "emavls\n" +
                "hbxwektuqjo\n" +
                "\n" +
                "qrhspwbulzkaxdm\n" +
                "auwbhyxlkdvq\n" +
                "\n" +
                "turdsw\n" +
                "utxrwsd\n" +
                "rtundsw\n" +
                "usdtrjwo\n" +
                "utdowrs\n" +
                "\n" +
                "gjro\n" +
                "gojm\n" +
                "\n" +
                "xhnilqdp\n" +
                "ienxaovqldkhg\n" +
                "\n" +
                "rgjonh\n" +
                "nvokcjqrt\n" +
                "argnjo\n" +
                "\n" +
                "jmgchqb\n" +
                "jivdabluqf\n" +
                "\n" +
                "ylmicxtahwqfvukneopgzsbrdj\n" +
                "hbzpeaqvlxgotsjkwmfndyiruc\n" +
                "\n" +
                "p\n" +
                "rop\n" +
                "\n" +
                "delgcpurwxniqohkvyas\n" +
                "gurxclnvdwbikoqezs\n" +
                "rnxewiqvgktmosfjd\n" +
                "\n" +
                "tigwskmhvupobfnydxcre\n" +
                "qwmdoycrhvsjptzxngbikue\n" +
                "yvmetfcbahuklxpdgowrisn\n" +
                "\n" +
                "wsy\n" +
                "wys\n" +
                "syjw\n" +
                "wys\n" +
                "yws\n" +
                "\n" +
                "srwpt\n" +
                "wtsrp\n" +
                "\n" +
                "lhafkqwscv\n" +
                "aklhcvrsqfw\n" +
                "vfsqckalwh\n" +
                "hlnqskcfvwa\n" +
                "klfwvzsdpacmhq\n" +
                "\n" +
                "ehbzglfvtdxpkicy\n" +
                "dl\n" +
                "jnmdl\n" +
                "wdsl\n" +
                "\n" +
                "rew\n" +
                "rek\n" +
                "ehi\n" +
                "ilehwkm\n" +
                "axe\n" +
                "\n" +
                "bl\n" +
                "hzlgey\n" +
                "\n" +
                "iboqgtdxprunz\n" +
                "uonzipxrgqbtd\n" +
                "\n" +
                "o\n" +
                "o\n" +
                "\n" +
                "bldk\n" +
                "bkpl\n" +
                "fklbc\n" +
                "\n" +
                "ynmuedqwhoktxprcavz\n" +
                "fshlwuznoymekqtprdv\n" +
                "\n" +
                "hjtwrzo\n" +
                "rowhztj\n" +
                "wuxrojhzt\n" +
                "ozjhrtw\n" +
                "hotzwjr\n" +
                "\n" +
                "senxaq\n" +
                "baen\n" +
                "ajmne\n" +
                "gaielnd\n" +
                "htfnpkuvwoae\n" +
                "\n" +
                "joklzmcuyg\n" +
                "uyzrifcmlkgsj\n" +
                "kyoumjcagblz\n" +
                "uytcgqklzjm\n" +
                "\n" +
                "ujvi\n" +
                "ijuv\n" +
                "epmijuv\n" +
                "viju\n" +
                "\n" +
                "tahxdeq\n" +
                "dazexot\n" +
                "baelxdq\n" +
                "pwexdgvyiukjcaf\n" +
                "edrnamzx\n" +
                "\n" +
                "zxqslwyh\n" +
                "shgyqlwxaz\n" +
                "\n" +
                "xbs\n" +
                "xbs\n" +
                "bsx\n" +
                "\n" +
                "kwlhvxy\n" +
                "kqwvlyxh\n" +
                "klvxwyqh\n" +
                "hxlkwvyq\n" +
                "kylwpvhxd\n" +
                "\n" +
                "koznivas\n" +
                "basiozvkn\n" +
                "ovzkluniash\n" +
                "ksnxcavioz\n" +
                "\n" +
                "g\n" +
                "g\n" +
                "g\n" +
                "g\n" +
                "shin\n" +
                "\n" +
                "e\n" +
                "qtvo\n" +
                "ac\n" +
                "ksw\n" +
                "ae\n" +
                "\n" +
                "pay\n" +
                "nau\n" +
                "a\n" +
                "\n" +
                "czkmwrvefultigxjhdqaopsnby\n" +
                "flqrbdxungowzkmjsyepvhitca\n" +
                "\n" +
                "ymw\n" +
                "vurft\n" +
                "\n" +
                "wqpgys\n" +
                "ywsq\n" +
                "qswy\n" +
                "qsyew\n" +
                "ywsq\n" +
                "\n" +
                "ndmo\n" +
                "fdoznkmw\n" +
                "hmuzndo\n" +
                "mtqdrnyo\n" +
                "uwfomnd\n" +
                "\n" +
                "pktnzsqhyvmaejclwuor\n" +
                "jwznystlkmqcraeovhup\n" +
                "vuwmteknjqohylazsrcp\n" +
                "\n" +
                "k\n" +
                "k\n" +
                "k\n" +
                "okxe\n" +
                "\n" +
                "fjilbxs\n" +
                "ib\n" +
                "bi\n" +
                "iqb\n" +
                "ibeq\n" +
                "\n" +
                "gjlyop\n" +
                "opglehyztj\n" +
                "jpclgymno\n" +
                "dopglymwj\n" +
                "gojplrbcy\n" +
                "\n" +
                "nuygowpxetsahrv\n" +
                "jgtpyhruwonexq\n" +
                "rlepnuikhgybxwot\n" +
                "svnygeuroxhzptqw\n" +
                "\n" +
                "wkies\n" +
                "eisqwk\n" +
                "kisew\n" +
                "eiwks\n" +
                "gxbkwsiep\n" +
                "\n" +
                "oj\n" +
                "joe\n" +
                "oj\n" +
                "jo\n" +
                "oj\n" +
                "\n" +
                "gtzunomec\n" +
                "cezutnko\n" +
                "tunzeco\n" +
                "cuoftneazk\n" +
                "\n" +
                "vpifjqnbcuaelxzgdwos\n" +
                "gfsyuwzclexopjvimqabd\n" +
                "\n" +
                "npaxeizolfrygctvw\n" +
                "rgtpxwicvafozenl\n" +
                "\n" +
                "e\n" +
                "e\n" +
                "p\n" +
                "t\n" +
                "e\n" +
                "\n" +
                "ohiaqmdktxnbpwlc\n" +
                "iqcopmavhwxbgnl\n" +
                "bhqaoiwxlpmcnzy\n" +
                "oxhwifeapuncblrmq\n" +
                "\n" +
                "wghbsijofevcu\n" +
                "qtlmkday\n" +
                "xlrznmp\n" +
                "\n" +
                "zbrjh\n" +
                "rzbjh\n" +
                "vebhzr\n" +
                "klrzhb\n" +
                "rjbhznl\n" +
                "\n" +
                "kcgzmvfrxebiautyohdwq\n" +
                "thdkgwzymrafbxecqiovus\n" +
                "rgtwzvocydiafmkqubehx\n" +
                "\n" +
                "i\n" +
                "ry\n" +
                "n\n" +
                "xgscp\n" +
                "\n" +
                "kzjngd\n" +
                "rdmwgnujzok\n" +
                "\n" +
                "djpivm\n" +
                "mdipjv\n" +
                "mlvdjip\n" +
                "\n" +
                "ilbdjmvfhyzxcqwuspn\n" +
                "lichmuxnzpqsyvwbfj\n" +
                "umnvlbiwqsfchxpzyj\n" +
                "uylzhpvfqbscijxmwn\n" +
                "clwjnihuyzpmqbxsfv\n" +
                "\n" +
                "o\n" +
                "o\n" +
                "fo\n" +
                "pon\n" +
                "\n" +
                "aowpk\n" +
                "zg\n" +
                "dt\n" +
                "uc\n" +
                "u\n" +
                "\n" +
                "ymhiouqp\n" +
                "lkyoqi\n" +
                "ywtsvqio\n" +
                "lnmyoiq\n" +
                "\n" +
                "ydbhigntrexvkua\n" +
                "urlaigkqnydwxhb\n" +
                "\n" +
                "nfro\n" +
                "z\n" +
                "jz\n" +
                "\n" +
                "ojsag\n" +
                "gajso\n" +
                "gjsao\n" +
                "jhsog\n" +
                "\n" +
                "t\n" +
                "t\n" +
                "y\n" +
                "h\n" +
                "\n" +
                "jieqmryxv\n" +
                "xqvimey\n" +
                "umyqveix\n" +
                "vtedmnxliqyf\n" +
                "\n" +
                "tmd\n" +
                "tdm\n" +
                "dtm\n" +
                "mkdt\n" +
                "hmdt\n" +
                "\n" +
                "px\n" +
                "gwruq\n" +
                "pz\n" +
                "\n" +
                "tejofhqklimp\n" +
                "thojpkfgelwmrq\n" +
                "\n" +
                "tseirdkyqvcghwju\n" +
                "tjhycvgilezdws\n" +
                "\n" +
                "roqbndl\n" +
                "rdql\n" +
                "qlrd\n" +
                "lqremd\n" +
                "\n" +
                "qvgunystzpckrwifmxdolajehb\n" +
                "bgtixcwloydzqjskvnfmpeurah\n" +
                "\n" +
                "soviern\n" +
                "rlakxngecptvsz\n" +
                "nvdsre\n" +
                "\n" +
                "gzkoiysxl\n" +
                "vjrlmtpbsceozhauwx\n" +
                "kfnqdzolsx\n" +
                "\n" +
                "kwzaqnipgxfhoy\n" +
                "hanwlofgqxpzk\n" +
                "xqngazkwphof\n" +
                "pqwkfghaoxzn\n" +
                "qwnfgpakxhzo\n" +
                "\n" +
                "zhurktfoqmlbnx\n" +
                "mhlxorzbntufqk\n" +
                "qbzklhnurmotfx\n" +
                "\n" +
                "gezmci\n" +
                "oecmg\n" +
                "\n" +
                "pcyteovnsz\n" +
                "dptlfuzh\n" +
                "\n" +
                "roxjhkng\n" +
                "xonksrad\n" +
                "rxnikos\n" +
                "\n" +
                "vbgmsrecxpj\n" +
                "srcjxmbgep\n" +
                "rbgsxcepjkmq\n" +
                "pjgcmzbsrxe\n" +
                "\n" +
                "gkvwndflryjshmbqxtpizuocea\n" +
                "fwndvekqtzployghijsmruabx\n" +
                "\n" +
                "dcxtogbifek\n" +
                "ifkdgoxbc\n" +
                "\n" +
                "srmqlnhbwv\n" +
                "liwsqzvtn\n" +
                "wgeoqvpfs\n" +
                "wkyqvsacd\n" +
                "\n" +
                "yswarofhdmqclxkgut\n" +
                "daxhzkgumjysrlwq\n" +
                "qfamswzyiglxdruhk\n" +
                "vsnwxadlhrbgqmuyk\n" +
                "\n" +
                "rxwzkmd\n" +
                "kwzx\n" +
                "qawokzlxe\n" +
                "xmdnfkwz\n" +
                "\n" +
                "exo\n" +
                "xvqod\n" +
                "cv\n" +
                "pnrkmywh\n" +
                "uztea\n" +
                "\n" +
                "ma\n" +
                "ma\n" +
                "qamfr\n" +
                "am\n" +
                "\n" +
                "nksp\n" +
                "kvpn\n" +
                "pkn\n" +
                "nkvp\n" +
                "nkp\n" +
                "\n" +
                "pwlvdsagy\n" +
                "islyawu\n" +
                "\n" +
                "sgbnwulekhpmy\n" +
                "mjgqeyshpbwuln\n" +
                "yubghpanecmszwlv\n" +
                "euwohbysqngptlmx\n" +
                "\n" +
                "gs\n" +
                "e\n" +
                "kas\n" +
                "a\n" +
                "md\n" +
                "\n" +
                "i\n" +
                "x\n" +
                "bl\n" +
                "\n" +
                "vishqyrzgmpbeuldj\n" +
                "gwcpvnskbftudyorj\n" +
                "\n" +
                "ueswlatkopc\n" +
                "wbeosclpktau\n" +
                "lcpvaswokuet\n" +
                "ltkupsmeawoc\n" +
                "\n" +
                "iwtvopbgyc\n" +
                "widjykopv\n" +
                "ivowyp\n" +
                "iwyvhop\n" +
                "\n" +
                "bfnwdumyozhpxre\n" +
                "zhweumdnpbofy\n" +
                "dcsobyuhfntpmzwe\n" +
                "\n" +
                "zrlaspbhty\n" +
                "oyhrftzbslap\n" +
                "ysztbhlapr\n" +
                "tszhpbayrl\n" +
                "\n" +
                "wbgxh\n" +
                "gnhwxcb\n" +
                "wxbhg\n" +
                "gxhwb\n" +
                "gxbwh\n" +
                "\n" +
                "ngribvdawujskcmfx\n" +
                "rvskbgiwjxuca\n" +
                "wiyvgcsbjxkrua\n" +
                "\n" +
                "ifstrq\n" +
                "fk\n" +
                "\n" +
                "b\n" +
                "b\n" +
                "b\n" +
                "u\n" +
                "\n" +
                "hpqy\n" +
                "wjplyq\n" +
                "\n" +
                "zwkfgbsmedluyot\n" +
                "fdtrhsgeumk\n" +
                "vexgtudkshfim\n" +
                "eutigskmdrf\n" +
                "\n" +
                "imljkdnzpx\n" +
                "jqwknpxlhmzd\n" +
                "pmdyxgnjklz\n" +
                "rxbjmlnkzdpg\n" +
                "ulxbmpdnzykj\n" +
                "\n" +
                "vetubnwdy\n" +
                "bnwatdvyou\n" +
                "zfwgvtdbnki\n" +
                "dlvewatnb\n" +
                "\n" +
                "uj\n" +
                "otuj\n" +
                "uj\n" +
                "\n" +
                "ifstpgrbcnywaxmkdzoqvh\n" +
                "qkbfhovrginxapzywdct\n" +
                "vyofbwcdginrkqtazhxp\n" +
                "\n" +
                "mvnaokugdshybwtr\n" +
                "ntvsywuadrkmohgb\n" +
                "\n" +
                "fauo\n" +
                "pnofxadk\n" +
                "sfoa\n" +
                "sofa\n" +
                "\n" +
                "akecpnjdwrztvlfbuhsiq\n" +
                "jehrndzisqcauwlftkbpv\n" +
                "uawiskrjentfbcqlpdvhz\n" +
                "crtpjbdalsviwfnhqezuk\n" +
                "ncawkfdsqtrhpjzielvub\n" +
                "\n" +
                "otazsfhc\n" +
                "ltkacysow\n" +
                "pvtomna\n" +
                "tacok\n" +
                "\n" +
                "mx\n" +
                "x\n" +
                "x\n" +
                "x\n" +
                "x\n" +
                "\n" +
                "hmoy\n" +
                "zmyhjuo\n" +
                "ypmxohn\n" +
                "hoxym\n" +
                "\n" +
                "dm\n" +
                "md\n" +
                "dm\n" +
                "md\n" +
                "\n" +
                "uqvbhfdomlwtkxez\n" +
                "szaqwmlhytgvxkr\n" +
                "wmpzhxqktlv\n" +
                "\n" +
                "btkpdjinsrmogfywzhlvecau\n" +
                "idylbvnopjsgrkfheuczawtm\n" +
                "tygvsizrwjneplkohcmafudb\n" +
                "wtvprskenjchmiyfuzglodba\n" +
                "jwdafzcemrbsunotyglpihkv\n" +
                "\n" +
                "e\n" +
                "ouxg\n" +
                "ei\n" +
                "shp\n" +
                "\n" +
                "ul\n" +
                "ul\n" +
                "ulrspe\n" +
                "louy\n" +
                "uynlvo\n" +
                "\n" +
                "yibgqkf\n" +
                "uvcwx\n" +
                "mvxdohjlw\n" +
                "\n" +
                "q\n" +
                "z\n" +
                "z\n" +
                "\n" +
                "orxgfiqznujyplsbadv\n" +
                "gtzieoxspqrvndjbylfu\n" +
                "\n" +
                "hmlqcujrysbgoentdp\n" +
                "dyjmrbtpuhgslncw\n" +
                "rmyfuhdgclnpsktjb\n" +
                "ptucnyhsmlwrbgjd\n" +
                "wrhnldscjeyupmtgb\n" +
                "\n" +
                "sowieczubgx\n" +
                "firsgewzpbo\n" +
                "\n" +
                "txeo\n" +
                "exot\n" +
                "oext\n" +
                "oxte\n" +
                "otxe\n" +
                "\n" +
                "ontlbzyekruhpscwqvaxmdj\n" +
                "ahrtijxdepnokymcsgwuf\n" +
                "\n" +
                "ftsraxmwogvnkdbzqiyhju\n" +
                "ylsdhonjzrfwmqukc\n" +
                "\n" +
                "leiupzardbfsv\n" +
                "dzuwlesifrbp\n" +
                "ldiupzersfb\n" +
                "fupwslrzbedi\n" +
                "\n" +
                "jtdp\n" +
                "dajg\n" +
                "\n" +
                "jpglzoriafexks\n" +
                "gpaozketlcixs\n" +
                "\n" +
                "butisvecnfplqmygworax\n" +
                "jrhpbwztcveifamlyqxdung\n" +
                "\n" +
                "r\n" +
                "r\n" +
                "r\n" +
                "zr\n" +
                "\n" +
                "eyniaztvgdrl\n" +
                "dalgonxbiecywthzvr\n" +
                "dtzrgenvliya\n" +
                "\n" +
                "akzferolcmstgby\n" +
                "kmcagsbteyrlfzo\n" +
                "aoktgslmcrzbfye\n" +
                "\n" +
                "jqigpeydwl\n" +
                "mkeaxqcudzgvfhb\n" +
                "\n" +
                "ayhgbfzerjxd\n" +
                "rnzfaxy\n" +
                "wyzaxnrf\n" +
                "ycazxfrw\n" +
                "ayzxrf\n" +
                "\n" +
                "jgmkwtnizxrcbvfqhyeal\n" +
                "mwatrngvlezckqfiybhjx\n" +
                "vmrwyqnigzhtjfckxaeb\n" +
                "wkehnqrtcjigzxavbfym\n" +
                "vrczmohgtfbnaejxqiwyk\n" +
                "\n" +
                "c\n" +
                "c\n" +
                "c\n" +
                "c\n" +
                "\n" +
                "idx\n" +
                "id\n" +
                "id\n" +
                "\n" +
                "zaipnjbsxkg\n" +
                "xevnfipkjgb\n" +
                "ujxldqcnbhi\n" +
                "\n" +
                "hco\n" +
                "co\n" +
                "\n" +
                "ztlrica\n" +
                "ktneixcrs\n" +
                "\n" +
                "hlutcdsgoj\n" +
                "mwlypnzbqafvxkire\n" +
                "\n" +
                "lznhjwgsiv\n" +
                "wricunaxj\n" +
                "\n" +
                "fdqgyzopwlen\n" +
                "rkvt\n" +
                "\n" +
                "vy\n" +
                "gy\n" +
                "\n" +
                "ihbpfsx\n" +
                "pshixfb\n" +
                "sifxhpb\n" +
                "\n" +
                "begmqirvflkxuyanp\n" +
                "dmpvhfbnaxsuloqitjy\n" +
                "\n" +
                "uwamykhsnbfzxielpdo\n" +
                "cxzswhvtabupmqjlekond\n" +
                "\n" +
                "gisqpjrubx\n" +
                "rjbiuqxspg\n" +
                "gqpirxbsju\n" +
                "\n" +
                "u\n" +
                "u\n" +
                "v\n" +
                "u\n" +
                "\n" +
                "gnjqsoha\n" +
                "qgandhlyrs\n" +
                "snhqvlrabg\n" +
                "\n" +
                "vo\n" +
                "vo\n" +
                "ov\n" +
                "vo\n" +
                "\n" +
                "iudvwxpmtac\n" +
                "owlyxsangim\n" +
                "hbdrxmwaei\n" +
                "wjimax\n" +
                "\n" +
                "xmubte\n" +
                "yuogxa\n" +
                "\n" +
                "nwkurtxjcpqozmhgsvbe\n" +
                "chrmvakuyxtowqpgzbej\n" +
                "\n" +
                "manbesvzpyt\n" +
                "dgtwazpqjmbnr\n" +
                "itfkoupbhlcnax\n" +
                "\n" +
                "omhinsxf\n" +
                "lnmdoix\n" +
                "eimgrno\n" +
                "hyomidn\n" +
                "nmjodi\n" +
                "\n" +
                "qmpn\n" +
                "ripmn\n" +
                "\n" +
                "wfm\n" +
                "wmf\n" +
                "mwf\n" +
                "mfw\n" +
                "fwm\n" +
                "\n" +
                "uaoxphg\n" +
                "phoxb\n" +
                "\n" +
                "btfprm\n" +
                "ztmrf\n" +
                "mrft\n" +
                "ramft\n" +
                "tmrezfa\n" +
                "\n" +
                "uaznory\n" +
                "zyaiourn\n" +
                "nouryaz\n" +
                "coszugmanyr\n" +
                "lqazryonu\n" +
                "\n" +
                "vqlswifmcg\n" +
                "wzuclnxsvt\n" +
                "\n" +
                "eh\n" +
                "eh\n" +
                "he\n" +
                "\n" +
                "siuhfpb\n" +
                "iuhfs\n" +
                "\n" +
                "yfhciqlnwpgemoxktas\n" +
                "ticjauwfsygepqnhx\n" +
                "\n" +
                "ndmhwtub\n" +
                "zbagktxiulnwh\n" +
                "\n" +
                "txdikm\n" +
                "boldxtiqmf\n" +
                "dxtimj\n" +
                "\n" +
                "wvr\n" +
                "vwrb\n" +
                "wrv\n" +
                "\n" +
                "utyjachpfordvw\n" +
                "benvkudcfta\n" +
                "vduqiftcgsa\n" +
                "fcuatdxv\n" +
                "\n" +
                "doivj\n" +
                "jiv\n" +
                "vjkpyi\n" +
                "jvi\n" +
                "dijv\n" +
                "\n" +
                "mhyn\n" +
                "mxngywh\n" +
                "yjhmn\n" +
                "dmynhulkacb\n" +
                "\n" +
                "hpidlbezkwqtr\n" +
                "dgtaflrnyscm\n" +
                "\n" +
                "osqeajcvduwhzrtkl\n" +
                "zcaevujrqsdolgwkyt\n" +
                "uokqnrdjaecvwtlzs\n" +
                "\n" +
                "ovsbxzgaju\n" +
                "vliydjht\n" +
                "dvjt\n" +
                "\n" +
                "stlxuabmcwqkodevrhf\n" +
                "ajskvtpmlicqewbhuzfd\n" +
                "\n" +
                "g\n" +
                "cg\n" +
                "ezfo\n" +
                "\n" +
                "zqfmuxlnhkgdpvwrtjio\n" +
                "rkjqvomtguhpiwfzxnld\n" +
                "zfgxrclnimokhvpjdutwq\n" +
                "tgkxfqrnhdzowpvijlmu\n" +
                "\n" +
                "ni\n" +
                "qn\n" +
                "nq\n" +
                "\n" +
                "sn\n" +
                "qn\n" +
                "fdn\n" +
                "qn\n" +
                "hson\n" +
                "\n" +
                "tplicyhxqfujbkzv\n" +
                "qfbzvwkuycsa\n" +
                "vzqnbfcokyuda\n" +
                "\n" +
                "apoy\n" +
                "plfxotkv\n" +
                "iphsqjorged\n" +
                "\n" +
                "ravyhbsfelgcmzponqwikj\n" +
                "bitfjzwakhmvxngsoepcyrlq\n" +
                "cevpwyrnlobjsfziagkhmq\n" +
                "mswnezcpklfrjqgiyovabdh\n" +
                "cijelkwpbnhrsmzofygavq\n" +
                "\n" +
                "sqvnuedcytaxohplzf\n" +
                "cekhbgwadpmyofslxq\n" +
                "\n" +
                "gclfnxakjzsw\n" +
                "wzjcnsgka\n" +
                "ciwzsganjk\n" +
                "aspicokjgnwz\n" +
                "\n" +
                "qrabg\n" +
                "ajbgmw\n" +
                "yabg\n" +
                "vgsrba\n" +
                "hcgtbya\n" +
                "\n" +
                "xarbuvi\n" +
                "ivaku\n" +
                "kiuav\n" +
                "vzgxiah\n" +
                "flsivaj\n" +
                "\n" +
                "ckodrthljgyfwm\n" +
                "mgytohfxnrdkjbvlwc\n" +
                "cfdwmjoltkshrgy\n" +
                "yhwmrldfucogkjt\n" +
                "fmctpgwydhkajlro\n" +
                "\n" +
                "qvibocelnsdyzfkjhpuxmtrg\n" +
                "zgdksnoypqebifltcrjvuxmh\n" +
                "giocmuefxsprhdjkzntvqlyb\n" +
                "\n" +
                "xkcrlwomygs\n" +
                "grluckhsanomxwf\n" +
                "sriokwlmcyxg\n" +
                "kxgirswtcvlom\n" +
                "\n" +
                "budr\n" +
                "brdu\n" +
                "dibur\n" +
                "urbd\n" +
                "\n" +
                "o\n" +
                "o\n" +
                "\n" +
                "p\n" +
                "p\n" +
                "p\n" +
                "p\n" +
                "\n" +
                "wnydf\n" +
                "wrptghizjqk\n" +
                "\n" +
                "wnbdmltxcq\n" +
                "dfcwl\n" +
                "\n" +
                "ksaveflzdxqocbgyjp\n" +
                "bcxavldgysqozpkjfe\n" +
                "ozpvselaqgbdycjxfk\n" +
                "clpzdoebvqjgaskxfy\n" +
                "qykodlgvzjaxspfceb\n" +
                "\n" +
                "nrmdjstqozklxvcyag\n" +
                "ejzwbu\n" +
                "\n" +
                "kfgijmd\n" +
                "zmgjdikf\n" +
                "jgimfdk\n" +
                "ijfgkmdz\n" +
                "smbrfkxdwgeij\n" +
                "\n" +
                "yhtuxnfcq\n" +
                "tcyufhnxq\n" +
                "hfuxytcqn\n" +
                "nqtufyxch\n" +
                "\n" +
                "rlhzknoiuycefpmvxqbg\n" +
                "nbvgfexmqikpyhruo\n" +
                "hqkgnvyieomubfxpr\n" +
                "\n" +
                "bjyadnftcsxqk\n" +
                "lpfbvzcsumerho\n" +
                "wctsbf\n" +
                "\n" +
                "iyamec\n" +
                "myeibctka\n" +
                "egyicam\n" +
                "\n" +
                "ac\n" +
                "pvaqdb\n" +
                "a\n" +
                "au\n" +
                "\n" +
                "giltsum\n" +
                "ixyhncbjqped\n" +
                "\n" +
                "cinzuvkystgfodr\n" +
                "rksphwcfxdgey\n" +
                "xrdjkygcsfq\n" +
                "bfmdecpysrkg\n" +
                "gcrdyslfk\n" +
                "\n" +
                "ayqpgucwedftoxjk\n" +
                "eoagwdtkfqlypjuc\n" +
                "\n" +
                "ktysxp\n" +
                "sptx\n" +
                "qpxst\n" +
                "ptsqx\n" +
                "\n" +
                "uvclismeajkpbzgqwn\n" +
                "aicbqfzvlnuegpm\n" +
                "glecvmpzrnioudaq\n" +
                "kanmveflzpcgyuqi\n" +
                "\n" +
                "vklag\n" +
                "glv\n" +
                "lvg\n" +
                "lgv\n" +
                "vgl\n" +
                "\n" +
                "tyuh\n" +
                "hut\n" +
                "thu\n" +
                "htu\n" +
                "thu\n" +
                "\n" +
                "eyipwtfuhxzalmdgrs\n" +
                "whfcvbquxgepn\n" +
                "\n" +
                "tg\n" +
                "ge\n" +
                "g\n" +
                "\n" +
                "vk\n" +
                "uatvn\n" +
                "mzv\n" +
                "\n" +
                "jhfmpux\n" +
                "mhjquxkp\n" +
                "\n" +
                "gzyxjwfb\n" +
                "grzfxmwybj\n" +
                "cywfjpxztgb\n" +
                "\n" +
                "udrye\n" +
                "eqdyr\n" +
                "yerd\n" +
                "eryd\n" +
                "\n" +
                "kwdoynribhpsqmlgvuje\n" +
                "gunbjywvmheirdqpok\n" +
                "dnqeivoptrkwuyjhmg\n" +
                "\n" +
                "czvmpr\n" +
                "sxpum\n" +
                "\n" +
                "qlktsn\n" +
                "tkclq\n" +
                "sbqlkwt\n" +
                "luetjiqpk\n" +
                "lcvtqsk\n" +
                "\n" +
                "rotvsfwelbnj\n" +
                "fwbqmaolesn\n" +
                "qbfwegzislpnoc\n" +
                "nzoelswfpab\n" +
                "\n" +
                "wsecbml\n" +
                "sclabmwe\n" +
                "ezpsidclwtmbgvr\n" +
                "mcelawsb\n" +
                "\n" +
                "ngz\n" +
                "zg\n" +
                "gz\n" +
                "zg\n" +
                "gz\n" +
                "\n" +
                "xqjwnaiyb\n" +
                "jayxibqngw\n" +
                "qinjwxbay\n" +
                "nbaiwyxqj\n" +
                "jniaxqwyb\n" +
                "\n" +
                "hktywl\n" +
                "htwlyk\n" +
                "kytwlh\n" +
                "\n" +
                "ymbeahldgz\n" +
                "pjaoszx\n" +
                "\n" +
                "b\n" +
                "b\n" +
                "bz\n" +
                "kb\n" +
                "\n" +
                "gvdcqp\n" +
                "qpvyrcdlk\n" +
                "\n" +
                "nij\n" +
                "jfiub\n" +
                "jtieyxl\n" +
                "mnij\n" +
                "imvju\n" +
                "\n" +
                "qh\n" +
                "hq\n" +
                "hq\n" +
                "hq\n" +
                "\n" +
                "tez\n" +
                "zet\n" +
                "etz\n" +
                "etz\n" +
                "\n" +
                "wz\n" +
                "wz\n" +
                "\n" +
                "xc\n" +
                "jvxc\n" +
                "xpzc\n" +
                "rgumxc\n" +
                "xc\n" +
                "\n" +
                "nizsgkvylw\n" +
                "ngylivwzks\n" +
                "ylgsiznvkw\n" +
                "ilgyvsankzw\n" +
                "ilzywsnkgv\n" +
                "\n" +
                "emhpiwfyung\n" +
                "qlzkob\n" +
                "ldjx\n" +
                "xvat\n" +
                "\n" +
                "luzfaswdyj\n" +
                "jsdyuzlafw\n" +
                "ljdsafzuwy\n" +
                "yusdjwzfal\n" +
                "dsyjwuzafl\n" +
                "\n" +
                "uioafnlegsvjdxphr\n" +
                "lnfrjdpehvsxguoa\n" +
                "najruefdlxogvhsp\n" +
                "\n" +
                "gumjphl\n" +
                "mplchdjuw\n" +
                "hmjrlup\n" +
                "jmpgulh\n" +
                "\n" +
                "q\n" +
                "q\n" +
                "q\n" +
                "q\n" +
                "q\n" +
                "\n" +
                "feyimktsugrq\n" +
                "qygsrtlpmfkeui\n" +
                "sfkmrgqyitue\n" +
                "\n" +
                "xpklzsyodcnhrjq\n" +
                "xcznojsdpqhrlky\n" +
                "\n" +
                "btmsc\n" +
                "mtscbv\n" +
                "csmtb\n" +
                "tmbcsx\n" +
                "mbxtsc\n" +
                "\n" +
                "dvrfumay\n" +
                "ymafr\n" +
                "mrifya\n" +
                "ykrmaf\n" +
                "\n" +
                "do\n" +
                "d\n" +
                "andk\n" +
                "dcp\n" +
                "d\n" +
                "\n" +
                "glhmjykfaznvrd\n" +
                "bvmijshzga\n" +
                "vmjuqazhgpx\n" +
                "voczhgamj\n" +
                "wjhizgqavms\n" +
                "\n" +
                "voilgtup\n" +
                "\n" +
                "vrphtmc\n" +
                "bgfkjvad\n" +
                "\n" +
                "bxkfi\n" +
                "kixbf\n" +
                "xfkbi\n" +
                "xfikb\n" +
                "xfkbi\n" +
                "\n" +
                "lfixvpozghcauk\n" +
                "plgixmzukcovh\n" +
                "hyruilocxgkztqv\n" +
                "uglxkaihcozv\n" +
                "\n" +
                "avgptdmi\n" +
                "gydpvt\n" +
                "dptawvu\n" +
                "rvtdopxlqs\n" +
                "\n" +
                "rsmglpt\n" +
                "gpmnlthr\n" +
                "\n" +
                "tqmeukoia\n" +
                "kamiout\n" +
                "mqwauekov\n" +
                "macoryuk\n" +
                "nujbskgapmlo\n" +
                "\n" +
                "ndjrglykwoi\n" +
                "jrwkdnolygi\n" +
                "ownkidlryjg\n" +
                "\n" +
                "kwheact\n" +
                "txukwjcgbhar\n" +
                "whgotjk\n" +
                "kzhtw\n" +
                "lmvynhptdqkifw\n" +
                "\n" +
                "odkzwylprhvn\n" +
                "pwozvnydrh\n" +
                "zdhnpryowv\n" +
                "\n" +
                "crni\n" +
                "qdnkiou\n" +
                "gbwhyasjx\n" +
                "\n" +
                "bxitsamogcq\n" +
                "erbxklyhvtczu\n" +
                "\n" +
                "swrfxdpjhly\n" +
                "pwdjkvfyxrshl\n" +
                "sxehqrtwpdamnyjzolbui\n" +
                "gpdryslhwxcj\n" +
                "\n" +
                "fhldcksrpyi\n" +
                "qfejshrcat\n" +
                "wsmrvcnogxh\n" +
                "\n" +
                "vwacyofjtilrxngp\n" +
                "otylvxpfwgcnjria\n" +
                "xojfignyrtlpwvca\n" +
                "\n" +
                "qvz\n" +
                "ozm\n" +
                "\n" +
                "msrdwqahutefvxy\n" +
                "rjmyotiefuh\n" +
                "ltyrmenbzjuhf\n" +
                "felbyputmhr\n" +
                "\n" +
                "riyzo\n" +
                "kzroyuwi\n" +
                "yirozp\n" +
                "yoirz\n" +
                "roiyz\n" +
                "\n" +
                "rqjz\n" +
                "vjrq\n" +
                "qrj\n" +
                "prqj\n" +
                "zqjr\n" +
                "\n" +
                "vdx\n" +
                "xvd\n" +
                "xdvu\n" +
                "vdx\n" +
                "\n" +
                "xeauhryviqg\n" +
                "wpxkufzsjmctlnybd\n" +
                "\n" +
                "hbzwdlno\n" +
                "tmrj\n" +
                "np\n" +
                "lqfx\n" +
                "kuygescvia\n" +
                "\n" +
                "iqph\n" +
                "ihpq\n" +
                "pqhi\n" +
                "ihqp\n" +
                "qpih\n" +
                "\n" +
                "lsfwxmpkgqzvhecoay\n" +
                "gqfszwakhvymptcexol\n" +
                "cpaxwlzkfqvhsgemyo\n" +
                "lghfwvcmzxpokeysaq\n" +
                "\n" +
                "tgmpafqbuds\n" +
                "hspdfabuqgctm\n" +
                "tpcubdaqsvgm\n" +
                "mxqbktspoaujd\n" +
                "\n" +
                "xktgfvyprhndme\n" +
                "vntmyskfegprid\n" +
                "dsvpfmnkygtre\n" +
                "ydmvpkfretng\n" +
                "\n" +
                "npvgjzuo\n" +
                "mwlackhs\n" +
                "\n" +
                "gyj\n" +
                "myk\n" +
                "\n" +
                "w\n" +
                "w\n" +
                "w\n" +
                "k\n" +
                "w\n" +
                "\n" +
                "sgrhv\n" +
                "rixdgjluf\n" +
                "rgs\n" +
                "rsbg\n" +
                "\n" +
                "kmiqobutwplfryxgeajhnz\n" +
                "ylrtmpauodjnfvwgeixqz\n" +
                "extlfwjsirnmgyuqaopz\n" +
                "\n" +
                "vdngfjbwypio\n" +
                "sukyvfzpeqwthdxg\n" +
                "fyvrndgbwp\n" +
                "ydwfvglp\n" +
                "\n" +
                "fhsi\n" +
                "hsbif\n" +
                "\n" +
                "fihzecojaqm\n" +
                "jzchuomvwsqfr\n" +
                "jzchoqtfm\n" +
                "\n" +
                "kqafdzcgphvbos\n" +
                "qbspzodfavhck\n" +
                "adfozhquktlcibspv\n" +
                "szhpfboagdcqkv\n" +
                "\n" +
                "tmeb\n" +
                "takbe\n" +
                "\n" +
                "ymrhgdo\n" +
                "ypgzhmltd\n" +
                "fdbymgshcx\n" +
                "nghyzldm\n" +
                "\n" +
                "bxgm\n" +
                "gmxb\n" +
                "mxgb\n" +
                "gxbm\n" +
                "xbmvg\n" +
                "\n" +
                "fep\n" +
                "lnp\n" +
                "trjim\n" +
                "dauy\n" +
                "fplk\n" +
                "\n" +
                "udhzexv\n" +
                "dhmezvx\n" +
                "qdxylbhvzw\n" +
                "zveduxcht\n" +
                "\n" +
                "wgvhaokesjirly\n" +
                "osrewigqfdyvzk\n" +
                "kupsxrimowgbe\n" +
                "\n" +
                "skzvhanpljbogdyxtiquw\n" +
                "xzgdwyjluhnbstopikaqv\n" +
                "pasixghzovnjylbwudqkt\n" +
                "\n" +
                "wj\n" +
                "wj\n" +
                "wkj\n" +
                "jw\n" +
                "wj\n" +
                "\n" +
                "nsmyxfhc\n" +
                "xcfymhsn\n" +
                "hxscmnyf\n" +
                "cfxsmnlyh\n" +
                "\n" +
                "jpblgmiyunazcfd\n" +
                "tabnyfmupclzgd\n" +
                "esyvuphfgwbknodzcxlqa\n" +
                "\n" +
                "xkyqozefvgutmrw\n" +
                "rmhzwgeutoypx\n" +
                "\n" +
                "rzaxcemljnvo\n" +
                "kdwyqvohesitfb\n" +
                "\n" +
                "kfqrcezwn\n" +
                "qrnwkzcf\n" +
                "frcnqwzk\n" +
                "frnckvhzwq\n" +
                "kqzrcnfw\n" +
                "\n" +
                "fqux\n" +
                "qxuyfod\n" +
                "ufxq\n" +
                "qxfu\n" +
                "qxuf\n" +
                "\n" +
                "ztopdir\n" +
                "ritpozd\n" +
                "otrpizd\n" +
                "idpotzr\n" +
                "\n" +
                "jzhngmufw\n" +
                "zguwhfj\n" +
                "\n" +
                "ndxhmysbgcriqkewoztujva\n" +
                "cmtwbudvysekqaxizrojng\n" +
                "itncgkdyoaxswrqvmejzpbu\n" +
                "qyvcdusgwbomejtxznkira\n" +
                "\n" +
                "nik\n" +
                "yfi\n" +
                "i\n" +
                "i\n" +
                "\n" +
                "hpsdjo\n" +
                "hobps\n" +
                "ohsp\n" +
                "shpo\n" +
                "kypshio\n" +
                "\n" +
                "jbiyatwz\n" +
                "zbtagnrc\n" +
                "ztnagb\n" +
                "batz\n" +
                "\n" +
                "fvkurj\n" +
                "kfgjvru\n" +
                "jukfrv\n" +
                "kvfujr";
    }
}
